on:
  push:
    branches:
    - main
name: TimeLog-Deploy

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build backend -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/timelog-backend:${{ github.sha }} -f ./backend/Dockerfile
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/timelog-backend:${{ github.sha }}

        - run: |
        
            docker build frontend -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/timelog-frontend:${{ github.sha }} -f ./frontend/Dockerfile --build-arg VITE_MSAL_CLIENT_ID=${{ secrets.VITE_MSAL_CLIENT_ID }} --build-arg VITE_MSAL_TENANT_ID=${{ secrets.VITE_MSAL_TENANT_ID }} --build-arg VITE_MSAL_REDIRECT_URI=${{ secrets.VITE_MSAL_REDIRECT_URI }} --build-arg VITE_MSAL_POST_LOGOUT_REDIRECT_URI=${{ secrets.VITE_MSAL_POST_LOGOUT_REDIRECT_URI }} 
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/timelog-frontend:${{ github.sha }}
